// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dduhjdzhxlwuuzidrzzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdWhqZHpoeGx3dXV6aWRyenppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Nzg4MzUsImV4cCI6MjA2ODI1NDgzNX0.x4Qc8vZJ3j_u14NE1O3NxjpZLRuOmnAKeBTW6AKJwDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});